version: '3.8'

services:
  mongo-express:
    image: mongo-express:latest
    container_name: helm-mongo-express
    ports:
      - "0.0.0.0:8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@helm-mongo-db:27017/
      ME_CONFIG_MONGODB_SERVER: helm-mongo-db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: admin # Optional: For Mongo Express login
      ME_CONFIG_BASICAUTH_PASSWORD: admin123 # Optional: For Mongo Express login
    networks:
      - helm-net
    env_file:
      - ../../.env # Point to the root .env file
    restart: unless-stopped

networks:
  helm-net:
    external: true