version: '3.8'

services:
  # ... other services like helm-backend, mcp-services etc.

  nats:
    image: nats:2.10
    container_name: helm-nats-bus
    ports:
      - "4222:4222" # Client port
      - "8222:8222" # HTTP monitoring port
    volumes:
      - /share/Dockers/Helm/services/nats/config/nats.conf:/etc/nats/nats.conf:ro
      - nats_data:/data/nats
    command: "-c /etc/nats/nats.conf"
    networks:
      - helm-net
    restart: unless-stopped

volumes:
  nats_data:
    driver: local

networks:
  helm-net:
    driver: bridge
